/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package osonapp;

import org.junit.Test;
import static org.junit.Assert.*;

public class OsonappTest {
    @Test public void testAppHasAGreeting() {
        Osonapp classUnderTest = new Osonapp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
